--  - LFO: Fix various features such as Length adjustment and clipboard.
--  - LFO: Fix misaligned display of current value.
--  - Fix knob range not working.
--  - LFO: Fix various features such as Length adjustment and clipboard.
--  - LFO: Fix misaligned display of current value.
--  - Fix knob range not working.
--  - LFO: Fix various features such as Length adjustment and clipboard.
--  - LFO: Fix misaligned display of current value.
--  - Fix knob range not working.
--  - LFO: Fix various features such as Length adjustment and clipboard.
--  - LFO: Fix misaligned display of current value.
--  - Fix knob range not wor